# Generated by Django 5.0.1 on 2025-08-08 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('study_abroad_app', '0003_blogcategory_blogpost'),
    ]

    operations = [
        migrations.RenameField(
            model_name='counsellormessage',
            old_name='name',
            new_name='first_name',
        ),
        migrations.RemoveField(
            model_name='counsellormessage',
            name='submitted_at',
        ),
        migrations.AddField(
            model_name='counsellormessage',
            name='city',
            field=models.CharField(default='Tamil Nadu', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='counsellormessage',
            name='last_name',
            field=models.CharField(default='A', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='counsellormessage',
            name='state',
            field=models.CharField(default='TamilNadu', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='counsellormessage',
            name='target_country',
            field=models.CharField(default='USA', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='counsellormessage',
            name='target_intake',
            field=models.CharField(default='may 2025', max_length=100),
            preserve_default=False,
        ),
    ]
