# Generated by Django 5.0.1 on 2025-08-08 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('study_abroad_app', '0004_rename_name_counsellormessage_first_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='counsellormessage',
            name='city',
        ),
        migrations.RemoveField(
            model_name='counsellormessage',
            name='last_name',
        ),
        migrations.AlterField(
            model_name='counsellormessage',
            name='phone',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='counsellormessage',
            name='state',
            field=models.CharField(choices=[('Kerala', 'Kerala'), ('Tamil Nadu', 'Tamil Nadu'), ('Karnataka', 'Karnataka')], max_length=100),
        ),
        migrations.AlterField(
            model_name='counsellormessage',
            name='target_country',
            field=models.CharField(choices=[('USA', 'USA'), ('UK', 'UK'), ('Canada', 'Canada')], max_length=100),
        ),
        migrations.AlterField(
            model_name='counsellormessage',
            name='target_intake',
            field=models.CharField(choices=[('Jan 2025', 'Jan 2025'), ('May 2025', 'May 2025'), ('Sep 2025', 'Sep 2025')], max_length=100),
        ),
    ]
