# Generated by Django 5.0.1 on 2025-08-08 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('study_abroad_app', '0005_remove_counsellormessage_city_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='counsellormessage',
            name='city',
            field=models.CharField(default='coTiruchirappalli', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='counsellormessage',
            name='last_name',
            field=models.CharField(default='A', max_length=100),
            preserve_default=False,
        ),
    ]
