# Generated by Django 5.0.1 on 2025-08-10 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('study_abroad_app', '0007_contactmessage'),
    ]

    operations = [
        migrations.CreateModel(
            name='MBBSPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('banner_title', models.CharField(max_length=200)),
                ('banner_image', models.ImageField(upload_to='mbbs/')),
                ('about_text', models.TextField()),
                ('why_choose_us', models.TextField()),
                ('benefits', models.TextField()),
            ],
        ),
    ]
