# Generated by Django 5.0.1 on 2025-08-10 06:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('study_abroad_app', '0008_mbbspage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mbbspage',
            name='banner_image',
        ),
        migrations.RemoveField(
            model_name='mbbspage',
            name='banner_title',
        ),
    ]
