# Generated by Django 5.0.1 on 2025-08-10 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('study_abroad_app', '0009_remove_mbbspage_banner_image_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MBACounsellingPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('about_text', models.TextField(help_text='Main description about MBA Counselling')),
                ('why_choose_us', models.TextField(blank=True, help_text='Bullet points for why choose us, one per line')),
                ('benefits', models.TextField(blank=True, help_text='Bullet points for benefits, one per line')),
            ],
        ),
    ]
