# Generated by Django 5.0.1 on 2025-08-11 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('study_abroad_app', '0010_mbacounsellingpage'),
    ]

    operations = [
        migrations.CreateModel(
            name='MSPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('about_text', models.TextField(help_text='Main description for the MS counselling page', verbose_name='About MS Counselling')),
                ('benefits_text', models.TextField(help_text='Key benefits for choosing MS abroad', verbose_name='Benefits of MS Abroad')),
                ('why_choose_text', models.TextField(help_text='Reasons to select MS abroad', verbose_name='Why Choose MS Abroad')),
            ],
        ),
    ]
