# Generated by Django 5.0.1 on 2025-08-11 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('study_abroad_app', '0011_mspage'),
    ]

    operations = [
        migrations.CreateModel(
            name='UndergradPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('about_text', models.TextField(help_text='Main description for undergraduate counselling page', verbose_name='About Undergraduate Counselling')),
                ('benefits_text', models.TextField(help_text='Key benefits for undergrad students abroad', verbose_name='Benefits of Studying Abroad')),
                ('why_choose_text', models.TextField(help_text='Reasons to choose our UG counselling services', verbose_name='Why Choose Our Counselling')),
            ],
        ),
    ]
