# Generated by Django 5.0.1 on 2025-08-11 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('study_abroad_app', '0014_ptepage'),
    ]

    operations = [
        migrations.CreateModel(
            name='TOEFLPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('about_text', models.TextField()),
                ('benefits_text', models.TextField()),
                ('why_choose_text', models.TextField()),
            ],
        ),
    ]
