# Generated by Django 5.0.1 on 2025-08-11 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('study_abroad_app', '0020_studentinsurancepage'),
    ]

    operations = [
        migrations.CreateModel(
            name='CountryPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(unique=True)),
                ('about_text', models.TextField()),
                ('benefits_text', models.TextField()),
                ('why_choose_text', models.TextField()),
            ],
        ),
    ]
