# Generated by Django 5.0.1 on 2025-08-11 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('study_abroad_app', '0021_countrypage'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(unique=True)),
                ('category', models.CharField(choices=[('counselling', 'Counselling'), ('testprep', 'Test Prep'), ('other', 'Other Services')], max_length=20)),
                ('description', models.TextField(blank=True)),
            ],
        ),
    ]
