# Generated by Django 5.0.1 on 2025-08-11 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('study_abroad_app', '0022_service'),
    ]

    operations = [
        migrations.RenameField(
            model_name='service',
            old_name='description',
            new_name='about_text',
        ),
        migrations.AddField(
            model_name='service',
            name='benefits_text',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='service',
            name='why_choose_text',
            field=models.TextField(blank=True),
        ),
    ]
