# Generated by Django 5.0.1 on 2025-08-11 12:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('study_abroad_app', '0023_rename_description_service_about_text_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EducationLoanPage',
        ),
        migrations.DeleteModel(
            name='ForeignExchangePage',
        ),
        migrations.DeleteModel(
            name='IELTSPage',
        ),
        migrations.DeleteModel(
            name='InternationalBankingPage',
        ),
        migrations.DeleteModel(
            name='MBACounsellingPage',
        ),
        migrations.DeleteModel(
            name='MBBSPage',
        ),
        migrations.DeleteModel(
            name='MSPage',
        ),
        migrations.DeleteModel(
            name='PTEPage',
        ),
        migrations.DeleteModel(
            name='StudentAccommodationPage',
        ),
        migrations.DeleteModel(
            name='StudentInsurancePage',
        ),
        migrations.DeleteModel(
            name='TOEFLPage',
        ),
        migrations.DeleteModel(
            name='UndergradPage',
        ),
    ]
