# Generated by Django 5.0.1 on 2025-08-12 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('study_abroad_app', '0024_delete_educationloanpage_delete_foreignexchangepage_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='about_us/')),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
