# Generated by Django 5.0.1 on 2025-08-13 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('study_abroad_app', '0026_aboutpage_delete_aboutus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='counsellormessage',
            name='state',
            field=models.CharField(choices=[('Andhra Pradesh', 'Andhra Pradesh'), ('Arunachal Pradesh', 'Arunachal Pradesh'), ('Assam', 'Assam'), ('Bihar', 'Bihar'), ('Chhattisgarh', 'Chhattisgarh'), ('Goa', 'Goa'), ('Gujarat', 'Gujarat'), ('Haryana', 'Haryana'), ('Himachal Pradesh', 'Himachal Pradesh'), ('Jharkhand', 'Jharkhand'), ('Karnataka', 'Karnataka'), ('Kerala', 'Kerala'), ('Madhya Pradesh', 'Madhya Pradesh'), ('Maharashtra', 'Maharashtra'), ('Manipur', 'Manipur'), ('Meghalaya', 'Meghalaya'), ('Mizoram', 'Mizoram'), ('Nagaland', 'Nagaland'), ('Odisha', 'Odisha'), ('Punjab', 'Punjab'), ('Rajasthan', 'Rajasthan'), ('Sikkim', 'Sikkim'), ('Tamil Nadu', 'Tamil Nadu'), ('Telangana', 'Telangana'), ('Tripura', 'Tripura'), ('Uttar Pradesh', 'Uttar Pradesh'), ('Uttarakhand', 'Uttarakhand'), ('West Bengal', 'West Bengal'), ('Andaman and Nicobar Islands', 'Andaman and Nicobar Islands'), ('Chandigarh', 'Chandigarh'), ('Dadra and Nagar Haveli and Daman and Diu', 'Dadra and Nagar Haveli and Daman and Diu'), ('Delhi', 'Delhi'), ('Jammu and Kashmir', 'Jammu and Kashmir'), ('Ladakh', 'Ladakh'), ('Lakshadweep', 'Lakshadweep'), ('Puducherry', 'Puducherry')], max_length=100),
        ),
        migrations.AlterField(
            model_name='counsellormessage',
            name='target_country',
            field=models.CharField(choices=[('USA', 'USA'), ('UK', 'UK'), ('Canada', 'Canada'), ('Australia', 'Australia'), ('France', 'France'), ('Irland', 'Irland'), ('Germany', 'Germany'), ('Newzealand', 'Newzealand')], max_length=100),
        ),
        migrations.AlterField(
            model_name='counsellormessage',
            name='target_intake',
            field=models.CharField(choices=[('Jan 2025', 'Jan 2025'), ('May 2025', 'May 2025'), ('Sep 2025', 'Sep 2025'), ('Jan 2026', 'Jan 2026'), ('May 2026', 'May 2026'), ('Sep 2026', 'Sep 2026'), ('Jan 2027', 'Jan 2027'), ('May 2027', 'May 2027'), ('Sep 2027', 'Sep 2027')], max_length=100),
        ),
    ]
