# Generated by Django 5.0.1 on 2025-08-13 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('study_abroad_app', '0027_alter_counsellormessage_state_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='counsellormessage',
            name='target_intake',
            field=models.CharField(choices=[('Jan 2025', 'Jan 2025'), ('May 2025', 'May 2025'), ('Sep 2025', 'Sep 2025'), ('Jan 2026', 'Jan 2026'), ('May 2026', 'May 2026'), ('Sep 2026', 'Sep 2026')], max_length=100),
        ),
    ]
