# Generated by Django 5.0.1 on 2025-08-13 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('study_abroad_app', '0028_alter_counsellormessage_target_intake'),
    ]

    operations = [
        migrations.AlterField(
            model_name='counsellormessage',
            name='message',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='counsellormessage',
            name='phone',
            field=models.CharField(max_length=15),
        ),
    ]
