# Generated by Django 5.0.1 on 2025-08-18 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('study_abroad_app', '0030_alter_counsellormessage_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='counsellormessage',
            name='state',
            field=models.CharField(choices=[('Andhra Pradesh', 'Andhra Pradesh'), ('Goa', 'Goa'), ('Gujarat', 'Gujarat'), ('Haryana', 'Haryana'), ('Jharkhand', 'Jharkhand'), ('Karnataka', 'Karnataka'), ('Kerala', 'Kerala'), ('Madhya Pradesh', 'Madhya Pradesh'), ('Maharashtra', 'Maharashtra'), ('Odisha', 'Odisha'), ('Tamil Nadu', 'Tamil Nadu'), ('Telangana', 'Telangana')], max_length=100),
        ),
        migrations.AlterField(
            model_name='counsellormessage',
            name='target_country',
            field=models.CharField(choices=[('USA', 'USA'), ('UK', 'UK'), ('Canada', 'Canada'), ('Australia', 'Australia'), ('France', 'France'), ('Ireland', 'Ireland'), ('Germany', 'Germany'), ('Newzealand', 'Newzealand'), ('UAE', 'UAE')], max_length=100),
        ),
    ]
