# Generated by Django 5.0.1 on 2025-08-18 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('study_abroad_app', '0033_alter_counsellormessage_state_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='counsellormessage',
            name='target_country',
            field=models.CharField(blank=True, choices=[('', 'Select Country'), ('USA', 'USA'), ('UK', 'UK'), ('Canada', 'Canada'), ('Australia', 'Australia'), ('France', 'France'), ('Ireland', 'Ireland'), ('Germany', 'Germany'), ('Newzealand', 'Newzealand'), ('UAE', 'UAE'), ('Other', 'Other')], max_length=100),
        ),
        migrations.AlterField(
            model_name='counsellormessage',
            name='target_intake',
            field=models.CharField(blank=True, choices=[('', 'Select Intake'), ('Jan 2025', 'Jan 2025'), ('May 2025', 'May 2025'), ('Sep 2025', 'Sep 2025'), ('Jan 2026', 'Jan 2026'), ('May 2026', 'May 2026'), ('Sep 2026', 'Sep 2026'), ('Other', 'Other')], max_length=100),
        ),
    ]
