# Generated by Django 5.0.1 on 2025-08-25 06:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('study_abroad_app', '0035_aboutdetail_aboutstat_teammember_testimonial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aboutdetail',
            name='why_choose_us',
        ),
        migrations.CreateModel(
            name='WhyChooseUsPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon_class', models.CharField(help_text='e.g., flaticon-student', max_length=50)),
                ('text', models.TextField()),
                ('about', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='why_choose_us_points', to='study_abroad_app.aboutdetail')),
            ],
        ),
    ]
